apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubernetes.io/enforce-mountable-secrets: "true"
  name: home

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: home
  labels:
    app: home
    service: home
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home
      service: home
  template:
    metadata:
      labels:
        app: home
        service: home
    spec:
      serviceAccountName: home
      
      containers:
      - name: home-container
        image: overseasdev/home:1.<version>
        ports:
        - containerPort: 80
        
        env: 