apiVersion: v1
kind: Service
metadata:
  name: home
  labels:
    app: home
    service: home
spec:
  selector:
    app: home
    service: home
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
